### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by SkillfulLupus** [risk-of-thunder/RoR2VersionSelector#2]
### What did you expect to happen?

to be able to boot up the game

### Instead of that, what actually happened?

it crashed

### Which operating system are you running on?

Windows

### Version

latest

### Additional Information

i backdated to 1.1.1.4 to play some older mods, now it just crashes on launch from steam or it's exe

**Comment by SkillfulLupus** [comment]
just ran it with admin privileges and tried copy the files over after it finished i tried launching through steam to a crash, booting the exe from the depot works perfectly fine it just doesn't work in steam

**Comment by chaslain** [comment]
@SkillfulLupus unless you can confirm that the files were not successfully copied over, an older version of the game crashing is out of the scope of this project. It is not out of the question that steam is confused by the older version and it just won't work in your environment. Since the game runs fine when not launched through steam, it would suggest the tool is not responsible for the failed launch.
